// Code generated by protoc-gen-go.
// source: pbtypes.proto
// DO NOT EDIT!

/*
Package skv is a generated protocol buffer package.

It is generated from these files:
	pbtypes.proto

It has these top-level messages:
	ValueMeta
*/
package skv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueMeta struct {
	Type    uint32 `protobuf:"varint,1,opt,name=Type,json=type" json:"Type,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=Version,json=version" json:"Version,omitempty"`
	Expired uint64 `protobuf:"varint,3,opt,name=Expired,json=expired" json:"Expired,omitempty"`
	Created uint64 `protobuf:"varint,4,opt,name=Created,json=created" json:"Created,omitempty"`
	Updated uint64 `protobuf:"varint,5,opt,name=Updated,json=updated" json:"Updated,omitempty"`
	Size    uint64 `protobuf:"varint,6,opt,name=Size,json=size" json:"Size,omitempty"`
	Sum     uint32 `protobuf:"varint,7,opt,name=Sum,json=sum" json:"Sum,omitempty"`
	Num     uint64 `protobuf:"varint,8,opt,name=Num,json=num" json:"Num,omitempty"`
	Name    string `protobuf:"bytes,13,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *ValueMeta) Reset()                    { *m = ValueMeta{} }
func (m *ValueMeta) String() string            { return proto.CompactTextString(m) }
func (*ValueMeta) ProtoMessage()               {}
func (*ValueMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ValueMeta) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ValueMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ValueMeta) GetExpired() uint64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *ValueMeta) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ValueMeta) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ValueMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ValueMeta) GetSum() uint32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *ValueMeta) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *ValueMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ValueMeta)(nil), "skv.ValueMeta")
}

func init() { proto.RegisterFile("pbtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8f, 0xbf, 0x6e, 0x83, 0x30,
	0x10, 0xc6, 0xe5, 0xda, 0x85, 0x62, 0x09, 0xa9, 0xf2, 0x74, 0x23, 0xea, 0xc4, 0xd4, 0xa5, 0x8f,
	0x50, 0x65, 0x0c, 0x03, 0x24, 0xec, 0x26, 0xdc, 0x60, 0x25, 0x06, 0xcb, 0x7f, 0x50, 0xe0, 0x35,
	0xf3, 0x42, 0x91, 0xed, 0xf1, 0xf7, 0xfd, 0xbe, 0xd3, 0xdd, 0xf1, 0xda, 0x4c, 0x7e, 0x37, 0xe8,
	0x7e, 0x8d, 0x5d, 0xfd, 0x2a, 0xa8, 0xbb, 0x6f, 0x3f, 0x2f, 0xc2, 0xab, 0x51, 0x3e, 0x02, 0x9e,
	0xd1, 0x4b, 0x21, 0x38, 0xbb, 0xec, 0x06, 0x81, 0x34, 0xa4, 0xad, 0x7b, 0x16, 0xdb, 0x02, 0x78,
	0x39, 0xa2, 0x75, 0x6a, 0x5d, 0xe0, 0xa3, 0x21, 0x2d, 0xeb, 0xcb, 0x2d, 0x63, 0x34, 0xa7, 0xa7,
	0x51, 0x16, 0x67, 0xa0, 0xd9, 0x60, 0xc6, 0x68, 0xfe, 0x2d, 0x4a, 0x8f, 0x33, 0xb0, 0x6c, 0x6e,
	0x19, 0xa3, 0xb9, 0x9a, 0x39, 0x99, 0xcf, 0x6c, 0x42, 0xc6, 0xb8, 0x7b, 0x50, 0x07, 0x42, 0x91,
	0x62, 0xe6, 0xd4, 0x81, 0xe2, 0x9b, 0xd3, 0x21, 0x68, 0x28, 0xd3, 0x39, 0xd4, 0x05, 0x1d, 0x93,
	0x2e, 0x68, 0xf8, 0x4a, 0x25, 0xba, 0x04, 0x1d, 0xe7, 0x3a, 0xa9, 0x11, 0xea, 0x86, 0xb4, 0x55,
	0xcf, 0x16, 0xa9, 0x71, 0x2a, 0xd2, 0x87, 0x7f, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x2f,
	0xac, 0x46, 0xf2, 0x00, 0x00, 0x00,
}
