// Code generated by protoc-gen-go.
// source: pbtypes.proto
// DO NOT EDIT!

/*
Package skv is a generated protocol buffer package.

It is generated from these files:
	pbtypes.proto

It has these top-level messages:
	MetaObject
	ValueObject
	ProgKeyEntry
	ProgKey
	ProgWriteOptions
	ProgKeyValueCommit
	ObjStorEntryMpInit
	ObjStorEntryMeta
	ObjStorEntryBlock
*/
package skv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetaObject struct {
	Type    uint32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	Expired uint64 `protobuf:"varint,3,opt,name=Expired" json:"Expired,omitempty"`
	Created uint64 `protobuf:"varint,4,opt,name=Created" json:"Created,omitempty"`
	Updated uint64 `protobuf:"varint,5,opt,name=Updated" json:"Updated,omitempty"`
	Size    uint64 `protobuf:"varint,6,opt,name=Size" json:"Size,omitempty"`
	Sum     uint32 `protobuf:"varint,7,opt,name=Sum" json:"Sum,omitempty"`
	Num     uint64 `protobuf:"varint,8,opt,name=Num" json:"Num,omitempty"`
	Name    string `protobuf:"bytes,13,opt,name=Name" json:"Name,omitempty"`
}

func (m *MetaObject) Reset()                    { *m = MetaObject{} }
func (m *MetaObject) String() string            { return proto.CompactTextString(m) }
func (*MetaObject) ProtoMessage()               {}
func (*MetaObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetaObject) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MetaObject) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MetaObject) GetExpired() uint64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *MetaObject) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *MetaObject) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *MetaObject) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *MetaObject) GetSum() uint32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *MetaObject) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *MetaObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ValueObject struct {
	Meta  *MetaObject `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Value []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ValueObject) Reset()                    { *m = ValueObject{} }
func (m *ValueObject) String() string            { return proto.CompactTextString(m) }
func (*ValueObject) ProtoMessage()               {}
func (*ValueObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ValueObject) GetMeta() *MetaObject {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ValueObject) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ProgKeyEntry struct {
	Type uint32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *ProgKeyEntry) Reset()                    { *m = ProgKeyEntry{} }
func (m *ProgKeyEntry) String() string            { return proto.CompactTextString(m) }
func (*ProgKeyEntry) ProtoMessage()               {}
func (*ProgKeyEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProgKeyEntry) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProgKeyEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProgKey struct {
	Items []*ProgKeyEntry `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ProgKey) Reset()                    { *m = ProgKey{} }
func (m *ProgKey) String() string            { return proto.CompactTextString(m) }
func (*ProgKey) ProtoMessage()               {}
func (*ProgKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProgKey) GetItems() []*ProgKeyEntry {
	if m != nil {
		return m.Items
	}
	return nil
}

type ProgWriteOptions struct {
	//    uint64     version      = 1;
	Actions uint64 `protobuf:"varint,2,opt,name=actions" json:"actions,omitempty"`
	Expired uint64 `protobuf:"varint,3,opt,name=expired" json:"expired,omitempty"`
	PrevSum uint32 `protobuf:"varint,4,opt,name=prev_sum,json=prevSum" json:"prev_sum,omitempty"`
}

func (m *ProgWriteOptions) Reset()                    { *m = ProgWriteOptions{} }
func (m *ProgWriteOptions) String() string            { return proto.CompactTextString(m) }
func (*ProgWriteOptions) ProtoMessage()               {}
func (*ProgWriteOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProgWriteOptions) GetActions() uint64 {
	if m != nil {
		return m.Actions
	}
	return 0
}

func (m *ProgWriteOptions) GetExpired() uint64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *ProgWriteOptions) GetPrevSum() uint32 {
	if m != nil {
		return m.PrevSum
	}
	return 0
}

type ProgKeyValueCommit struct {
	Meta    *MetaObject       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Key     *ProgKey          `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value   []byte            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Options *ProgWriteOptions `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
}

func (m *ProgKeyValueCommit) Reset()                    { *m = ProgKeyValueCommit{} }
func (m *ProgKeyValueCommit) String() string            { return proto.CompactTextString(m) }
func (*ProgKeyValueCommit) ProtoMessage()               {}
func (*ProgKeyValueCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProgKeyValueCommit) GetMeta() *MetaObject {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ProgKeyValueCommit) GetKey() *ProgKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProgKeyValueCommit) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProgKeyValueCommit) GetOptions() *ProgWriteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ObjStorEntryMpInit struct {
	Path  string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Size  uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Attrs uint64 `protobuf:"varint,5,opt,name=attrs" json:"attrs,omitempty"`
}

func (m *ObjStorEntryMpInit) Reset()                    { *m = ObjStorEntryMpInit{} }
func (m *ObjStorEntryMpInit) String() string            { return proto.CompactTextString(m) }
func (*ObjStorEntryMpInit) ProtoMessage()               {}
func (*ObjStorEntryMpInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ObjStorEntryMpInit) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ObjStorEntryMpInit) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjStorEntryMpInit) GetAttrs() uint64 {
	if m != nil {
		return m.Attrs
	}
	return 0
}

type ObjStorEntryMeta struct {
	Meta      *MetaObject `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Path      string      `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Size      uint64      `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Attrs     uint64      `protobuf:"varint,5,opt,name=attrs" json:"attrs,omitempty"`
	Sn        uint32      `protobuf:"varint,7,opt,name=sn" json:"sn,omitempty"`
	CommitKey string      `protobuf:"bytes,8,opt,name=commit_key,json=commitKey" json:"commit_key,omitempty"`
	Blocks    []uint32    `protobuf:"varint,9,rep,packed,name=blocks" json:"blocks,omitempty"`
}

func (m *ObjStorEntryMeta) Reset()                    { *m = ObjStorEntryMeta{} }
func (m *ObjStorEntryMeta) String() string            { return proto.CompactTextString(m) }
func (*ObjStorEntryMeta) ProtoMessage()               {}
func (*ObjStorEntryMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ObjStorEntryMeta) GetMeta() *MetaObject {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ObjStorEntryMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ObjStorEntryMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjStorEntryMeta) GetAttrs() uint64 {
	if m != nil {
		return m.Attrs
	}
	return 0
}

func (m *ObjStorEntryMeta) GetSn() uint32 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *ObjStorEntryMeta) GetCommitKey() string {
	if m != nil {
		return m.CommitKey
	}
	return ""
}

func (m *ObjStorEntryMeta) GetBlocks() []uint32 {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ObjStorEntryBlock struct {
	Meta      *MetaObject `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Path      string      `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Size      uint64      `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Attrs     uint64      `protobuf:"varint,5,opt,name=attrs" json:"attrs,omitempty"`
	Num       uint32      `protobuf:"varint,6,opt,name=num" json:"num,omitempty"`
	Sum       uint64      `protobuf:"varint,7,opt,name=sum" json:"sum,omitempty"`
	Sn        uint32      `protobuf:"varint,8,opt,name=sn" json:"sn,omitempty"`
	Data      []byte      `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	CommitKey string      `protobuf:"bytes,10,opt,name=commit_key,json=commitKey" json:"commit_key,omitempty"`
}

func (m *ObjStorEntryBlock) Reset()                    { *m = ObjStorEntryBlock{} }
func (m *ObjStorEntryBlock) String() string            { return proto.CompactTextString(m) }
func (*ObjStorEntryBlock) ProtoMessage()               {}
func (*ObjStorEntryBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ObjStorEntryBlock) GetMeta() *MetaObject {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ObjStorEntryBlock) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ObjStorEntryBlock) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjStorEntryBlock) GetAttrs() uint64 {
	if m != nil {
		return m.Attrs
	}
	return 0
}

func (m *ObjStorEntryBlock) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *ObjStorEntryBlock) GetSum() uint64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *ObjStorEntryBlock) GetSn() uint32 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *ObjStorEntryBlock) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ObjStorEntryBlock) GetCommitKey() string {
	if m != nil {
		return m.CommitKey
	}
	return ""
}

func init() {
	proto.RegisterType((*MetaObject)(nil), "skv.MetaObject")
	proto.RegisterType((*ValueObject)(nil), "skv.ValueObject")
	proto.RegisterType((*ProgKeyEntry)(nil), "skv.ProgKeyEntry")
	proto.RegisterType((*ProgKey)(nil), "skv.ProgKey")
	proto.RegisterType((*ProgWriteOptions)(nil), "skv.ProgWriteOptions")
	proto.RegisterType((*ProgKeyValueCommit)(nil), "skv.ProgKeyValueCommit")
	proto.RegisterType((*ObjStorEntryMpInit)(nil), "skv.ObjStorEntryMpInit")
	proto.RegisterType((*ObjStorEntryMeta)(nil), "skv.ObjStorEntryMeta")
	proto.RegisterType((*ObjStorEntryBlock)(nil), "skv.ObjStorEntryBlock")
}

func init() { proto.RegisterFile("pbtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xd6, 0x66, 0x37, 0x7f, 0x93, 0x2c, 0xa4, 0x16, 0x20, 0x73, 0x00, 0x45, 0xcb, 0x81, 0x9c,
	0x82, 0x14, 0x24, 0x1e, 0xa0, 0xa5, 0x52, 0x11, 0x6a, 0x83, 0x1c, 0x28, 0xc7, 0xca, 0x49, 0x2c,
	0xd8, 0xa6, 0xbb, 0x6b, 0xd9, 0xde, 0x88, 0xf0, 0x34, 0x3c, 0x08, 0x8f, 0xc1, 0x95, 0x77, 0x41,
	0x33, 0x76, 0xda, 0x6d, 0xc5, 0xa1, 0x12, 0x12, 0xb7, 0xef, 0x9b, 0x6f, 0xc7, 0x9e, 0xef, 0xd3,
	0x78, 0x21, 0xd5, 0x4b, 0xb7, 0xd3, 0xca, 0x4e, 0xb5, 0xa9, 0x5c, 0xc5, 0x62, 0xbb, 0xd9, 0x66,
	0xbf, 0x22, 0x80, 0x53, 0xe5, 0xe4, 0x7c, 0x79, 0xa9, 0x56, 0x8e, 0x31, 0x48, 0x3e, 0xee, 0xb4,
	0xe2, 0xd1, 0x38, 0x9a, 0xa4, 0x82, 0x30, 0xe3, 0xd0, 0x3d, 0x57, 0xc6, 0xe6, 0x55, 0xc9, 0x5b,
	0xe3, 0x68, 0x92, 0x88, 0x3d, 0x45, 0xe5, 0xf8, 0x9b, 0xce, 0x8d, 0x5a, 0xf3, 0xd8, 0x2b, 0x81,
	0xa2, 0x72, 0x64, 0x94, 0x74, 0x6a, 0xcd, 0x13, 0xaf, 0x04, 0x8a, 0xca, 0x27, 0xbd, 0x26, 0xa5,
	0xed, 0x95, 0x40, 0xf1, 0xee, 0x45, 0xfe, 0x5d, 0xf1, 0x0e, 0x95, 0x09, 0xb3, 0x11, 0xc4, 0x8b,
	0xba, 0xe0, 0x5d, 0x1a, 0x07, 0x21, 0x56, 0xce, 0xea, 0x82, 0xf7, 0xe8, 0x23, 0x84, 0xd8, 0x77,
	0x26, 0x0b, 0xc5, 0xd3, 0x71, 0x34, 0xe9, 0x0b, 0xc2, 0xd9, 0x09, 0x0c, 0xce, 0xe5, 0x55, 0xad,
	0x82, 0xad, 0x17, 0x90, 0x14, 0xca, 0x49, 0xb2, 0x35, 0x98, 0x3d, 0x9c, 0xda, 0xcd, 0x76, 0x7a,
	0xe3, 0x5a, 0x90, 0xc8, 0x1e, 0x41, 0x7b, 0x8b, 0x3d, 0xe4, 0x72, 0x28, 0x3c, 0xc9, 0xde, 0xc0,
	0xf0, 0x83, 0xa9, 0xbe, 0xbc, 0x57, 0xbb, 0xe3, 0xd2, 0x99, 0xdd, 0x5f, 0x13, 0x62, 0x90, 0xbc,
	0x95, 0x4e, 0x86, 0x46, 0xc2, 0xd9, 0x0c, 0xba, 0xa1, 0x8f, 0xbd, 0x84, 0x76, 0xee, 0x54, 0x61,
	0x79, 0x34, 0x8e, 0x27, 0x83, 0xd9, 0x01, 0x5d, 0xdf, 0x3c, 0x54, 0x78, 0x3d, 0x93, 0x30, 0xc2,
	0xf2, 0x67, 0x93, 0x3b, 0x35, 0xd7, 0x2e, 0xaf, 0x4a, 0x8b, 0x79, 0xc9, 0x15, 0xc1, 0x7d, 0xfa,
	0x81, 0xa2, 0xa2, 0x6e, 0xa7, 0x1f, 0x28, 0x7b, 0x0a, 0x3d, 0x6d, 0xd4, 0xf6, 0xc2, 0xd6, 0x05,
	0xc5, 0x9f, 0x8a, 0x2e, 0xf2, 0x45, 0x5d, 0x64, 0x3f, 0x22, 0x60, 0xe1, 0x6a, 0x0a, 0xe8, 0xa8,
	0x2a, 0x8a, 0xfc, 0x9e, 0x01, 0x3d, 0x87, 0x78, 0xa3, 0x76, 0x34, 0xc6, 0x60, 0x36, 0x6c, 0xba,
	0x10, 0x28, 0xdc, 0x04, 0x18, 0x37, 0x02, 0x64, 0xaf, 0xa0, 0x5b, 0x79, 0x2f, 0x34, 0xcb, 0x60,
	0xf6, 0xf8, 0xba, 0xb3, 0x69, 0x54, 0xec, 0xbf, 0xca, 0x04, 0xb0, 0xf9, 0xf2, 0x72, 0xe1, 0x2a,
	0x43, 0xe1, 0x9c, 0xea, 0x77, 0x65, 0x4e, 0x9b, 0xa9, 0xa5, 0xfb, 0x4a, 0x67, 0xf7, 0x05, 0x61,
	0xac, 0x59, 0xdc, 0x18, 0xbf, 0x62, 0x84, 0x71, 0x08, 0xe9, 0x9c, 0xb1, 0x61, 0xbb, 0x3c, 0xc9,
	0x7e, 0x46, 0x30, 0xba, 0x75, 0x28, 0xfa, 0xb9, 0x97, 0xe9, 0x7f, 0xba, 0x97, 0x3d, 0x80, 0x96,
	0x2d, 0xc3, 0xfa, 0xb6, 0x6c, 0xc9, 0x9e, 0x01, 0xac, 0x28, 0xf1, 0x0b, 0x4c, 0xb2, 0x47, 0x67,
	0xf6, 0x7d, 0x05, 0x37, 0xe5, 0x09, 0x74, 0x96, 0x57, 0xd5, 0x6a, 0x63, 0x79, 0x7f, 0x1c, 0x4f,
	0x52, 0x11, 0x58, 0xf6, 0x3b, 0x82, 0x83, 0xe6, 0xf8, 0x87, 0x58, 0xfe, 0x1f, 0xf3, 0x8f, 0x20,
	0x2e, 0xeb, 0x82, 0x9e, 0x64, 0x2a, 0x10, 0x62, 0xc5, 0x86, 0x17, 0x99, 0x08, 0x84, 0xc1, 0x63,
	0xef, 0xda, 0x23, 0x83, 0x64, 0x8d, 0xaf, 0xa1, 0xef, 0x5f, 0x03, 0xe2, 0x3b, 0xbe, 0xe1, 0x8e,
	0xef, 0xc3, 0xd6, 0x49, 0xbc, 0xec, 0xd0, 0x5f, 0xe9, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x11, 0xbd, 0xdb, 0xa6, 0x04, 0x00, 0x00,
}
