// Code generated by protoc-gen-go.
// source: pbtypes.proto
// DO NOT EDIT!

/*
Package iotypes is a generated protocol buffer package.

It is generated from these files:
	pbtypes.proto

It has these top-level messages:
	ErrorMeta
	ValueMeta
*/
package iotypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorMeta struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorMeta) Reset()                    { *m = ErrorMeta{} }
func (m *ErrorMeta) String() string            { return proto.CompactTextString(m) }
func (*ErrorMeta) ProtoMessage()               {}
func (*ErrorMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorMeta) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorMeta) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValueMeta struct {
	Version uint64 `protobuf:"varint,1,opt,name=Version,json=version" json:"Version,omitempty"`
	Expired uint64 `protobuf:"varint,2,opt,name=Expired,json=expired" json:"Expired,omitempty"`
	Created uint64 `protobuf:"varint,3,opt,name=Created,json=created" json:"Created,omitempty"`
	Updated uint64 `protobuf:"varint,4,opt,name=Updated,json=updated" json:"Updated,omitempty"`
	Size    uint64 `protobuf:"varint,5,opt,name=Size,json=size" json:"Size,omitempty"`
	Sum     uint32 `protobuf:"varint,6,opt,name=Sum,json=sum" json:"Sum,omitempty"`
	Name    string `protobuf:"bytes,7,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *ValueMeta) Reset()                    { *m = ValueMeta{} }
func (m *ValueMeta) String() string            { return proto.CompactTextString(m) }
func (*ValueMeta) ProtoMessage()               {}
func (*ValueMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ValueMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ValueMeta) GetExpired() uint64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *ValueMeta) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ValueMeta) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ValueMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ValueMeta) GetSum() uint32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *ValueMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorMeta)(nil), "iotypes.ErrorMeta")
	proto.RegisterType((*ValueMeta)(nil), "iotypes.ValueMeta")
}

func init() { proto.RegisterFile("pbtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xbd, 0x6a, 0x04, 0x21,
	0x14, 0x85, 0x31, 0x63, 0x56, 0x46, 0x58, 0x08, 0x56, 0xb7, 0x5c, 0xb6, 0xda, 0x2a, 0x4d, 0xaa,
	0xd4, 0x61, 0xca, 0xa4, 0x70, 0xc8, 0xf4, 0xce, 0x78, 0x09, 0x42, 0x1c, 0xc5, 0x9f, 0x90, 0xcc,
	0x3b, 0xe5, 0x1d, 0x83, 0x57, 0xd2, 0xf9, 0x9d, 0xcf, 0x23, 0x1e, 0x79, 0x8e, 0x6b, 0xf9, 0x89,
	0x98, 0x1f, 0x63, 0x0a, 0x25, 0x28, 0xe1, 0x02, 0xe1, 0xf5, 0x59, 0x8e, 0x53, 0x4a, 0x21, 0xbd,
	0x62, 0x31, 0x4a, 0x49, 0xbe, 0x05, 0x8b, 0xc0, 0x2e, 0xec, 0x36, 0x6a, 0x3a, 0x2b, 0x90, 0xc2,
	0x63, 0xce, 0xe6, 0x03, 0xe1, 0x8e, 0xe2, 0x7f, 0xbc, 0xfe, 0x32, 0x39, 0x2e, 0xe6, 0xb3, 0x22,
	0x75, 0x41, 0x8a, 0x05, 0x53, 0x76, 0x61, 0xa7, 0x3a, 0xd7, 0xe2, 0xab, 0x63, 0x33, 0xd3, 0x77,
	0x74, 0x09, 0x2d, 0xbd, 0xc0, 0xb5, 0xc0, 0x8e, 0xcd, 0xbc, 0x24, 0x34, 0x05, 0x2d, 0x0c, 0xdd,
	0x6c, 0x1d, 0x9b, 0x79, 0x8f, 0x96, 0x0c, 0xef, 0xa6, 0x76, 0x6c, 0x7f, 0x9c, 0xdd, 0x81, 0x70,
	0x4f, 0x31, 0xcf, 0xee, 0x40, 0xf5, 0x20, 0x87, 0xb9, 0x7a, 0x38, 0x5d, 0xd8, 0xed, 0xac, 0x87,
	0x5c, 0x7d, 0xbb, 0xf5, 0x66, 0x3c, 0x82, 0xe8, 0x4b, 0x76, 0xe3, 0x71, 0x3d, 0xd1, 0xf4, 0xa7,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xf3, 0x70, 0x10, 0x0b, 0x01, 0x00, 0x00,
}
