// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sko.proto

package sko

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectMeta struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	IncrId               uint64   `protobuf:"varint,3,opt,name=incr_id,json=incrId" json:"incr_id,omitempty"`
	Created              uint64   `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Updated              uint64   `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	Expired              uint64   `protobuf:"varint,11,opt,name=expired" json:"expired,omitempty"`
	DataAttrs            uint64   `protobuf:"varint,12,opt,name=data_attrs,json=dataAttrs" json:"data_attrs,omitempty"`
	DataCheck            uint64   `protobuf:"varint,13,opt,name=data_check,json=dataCheck" json:"data_check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{0}
}
func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (dst *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(dst, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ObjectMeta) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ObjectMeta) GetIncrId() uint64 {
	if m != nil {
		return m.IncrId
	}
	return 0
}

func (m *ObjectMeta) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ObjectMeta) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ObjectMeta) GetExpired() uint64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *ObjectMeta) GetDataAttrs() uint64 {
	if m != nil {
		return m.DataAttrs
	}
	return 0
}

func (m *ObjectMeta) GetDataCheck() uint64 {
	if m != nil {
		return m.DataCheck
	}
	return 0
}

type ObjectData struct {
	Attrs                uint64   `protobuf:"varint,8,opt,name=attrs" json:"attrs,omitempty"`
	Check                uint64   `protobuf:"varint,9,opt,name=check" json:"check,omitempty"`
	Value                []byte   `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectData) Reset()         { *m = ObjectData{} }
func (m *ObjectData) String() string { return proto.CompactTextString(m) }
func (*ObjectData) ProtoMessage()    {}
func (*ObjectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{1}
}
func (m *ObjectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectData.Unmarshal(m, b)
}
func (m *ObjectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectData.Marshal(b, m, deterministic)
}
func (dst *ObjectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectData.Merge(dst, src)
}
func (m *ObjectData) XXX_Size() int {
	return xxx_messageInfo_ObjectData.Size(m)
}
func (m *ObjectData) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectData.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectData proto.InternalMessageInfo

func (m *ObjectData) GetAttrs() uint64 {
	if m != nil {
		return m.Attrs
	}
	return 0
}

func (m *ObjectData) GetCheck() uint64 {
	if m != nil {
		return m.Check
	}
	return 0
}

func (m *ObjectData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ObjectItem struct {
	Meta                 *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Data                 *ObjectData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectItem) Reset()         { *m = ObjectItem{} }
func (m *ObjectItem) String() string { return proto.CompactTextString(m) }
func (*ObjectItem) ProtoMessage()    {}
func (*ObjectItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{2}
}
func (m *ObjectItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectItem.Unmarshal(m, b)
}
func (m *ObjectItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectItem.Marshal(b, m, deterministic)
}
func (dst *ObjectItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectItem.Merge(dst, src)
}
func (m *ObjectItem) XXX_Size() int {
	return xxx_messageInfo_ObjectItem.Size(m)
}
func (m *ObjectItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectItem.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectItem proto.InternalMessageInfo

func (m *ObjectItem) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ObjectItem) GetData() *ObjectData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ObjectReader struct {
	Mode                 uint64   `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	LimitNum             int64    `protobuf:"varint,8,opt,name=limit_num,json=limitNum" json:"limit_num,omitempty"`
	LimitSize            int64    `protobuf:"varint,9,opt,name=limit_size,json=limitSize" json:"limit_size,omitempty"`
	KeyOffset            []byte   `protobuf:"bytes,12,opt,name=key_offset,json=keyOffset,proto3" json:"key_offset,omitempty"`
	KeyCutset            []byte   `protobuf:"bytes,13,opt,name=key_cutset,json=keyCutset,proto3" json:"key_cutset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectReader) Reset()         { *m = ObjectReader{} }
func (m *ObjectReader) String() string { return proto.CompactTextString(m) }
func (*ObjectReader) ProtoMessage()    {}
func (*ObjectReader) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{3}
}
func (m *ObjectReader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectReader.Unmarshal(m, b)
}
func (m *ObjectReader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectReader.Marshal(b, m, deterministic)
}
func (dst *ObjectReader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectReader.Merge(dst, src)
}
func (m *ObjectReader) XXX_Size() int {
	return xxx_messageInfo_ObjectReader.Size(m)
}
func (m *ObjectReader) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectReader.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectReader proto.InternalMessageInfo

func (m *ObjectReader) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *ObjectReader) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ObjectReader) GetLimitNum() int64 {
	if m != nil {
		return m.LimitNum
	}
	return 0
}

func (m *ObjectReader) GetLimitSize() int64 {
	if m != nil {
		return m.LimitSize
	}
	return 0
}

func (m *ObjectReader) GetKeyOffset() []byte {
	if m != nil {
		return m.KeyOffset
	}
	return nil
}

func (m *ObjectReader) GetKeyCutset() []byte {
	if m != nil {
		return m.KeyCutset
	}
	return nil
}

type ObjectWriter struct {
	Meta                 *ObjectMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Data                 *ObjectData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	PrevVersion          uint64      `protobuf:"varint,5,opt,name=prev_version,json=prevVersion" json:"prev_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectWriter) Reset()         { *m = ObjectWriter{} }
func (m *ObjectWriter) String() string { return proto.CompactTextString(m) }
func (*ObjectWriter) ProtoMessage()    {}
func (*ObjectWriter) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{4}
}
func (m *ObjectWriter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectWriter.Unmarshal(m, b)
}
func (m *ObjectWriter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectWriter.Marshal(b, m, deterministic)
}
func (dst *ObjectWriter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectWriter.Merge(dst, src)
}
func (m *ObjectWriter) XXX_Size() int {
	return xxx_messageInfo_ObjectWriter.Size(m)
}
func (m *ObjectWriter) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectWriter.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectWriter proto.InternalMessageInfo

func (m *ObjectWriter) GetMeta() *ObjectMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ObjectWriter) GetData() *ObjectData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ObjectWriter) GetPrevVersion() uint64 {
	if m != nil {
		return m.PrevVersion
	}
	return 0
}

type ObjectResult struct {
	Status               uint64        `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Items                []*ObjectItem `protobuf:"bytes,9,rep,name=items" json:"items,omitempty"`
	Next                 bool          `protobuf:"varint,12,opt,name=next" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectResult) Reset()         { *m = ObjectResult{} }
func (m *ObjectResult) String() string { return proto.CompactTextString(m) }
func (*ObjectResult) ProtoMessage()    {}
func (*ObjectResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_sko_d2bc4f079416d69d, []int{5}
}
func (m *ObjectResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectResult.Unmarshal(m, b)
}
func (m *ObjectResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectResult.Marshal(b, m, deterministic)
}
func (dst *ObjectResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectResult.Merge(dst, src)
}
func (m *ObjectResult) XXX_Size() int {
	return xxx_messageInfo_ObjectResult.Size(m)
}
func (m *ObjectResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectResult.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectResult proto.InternalMessageInfo

func (m *ObjectResult) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ObjectResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ObjectResult) GetItems() []*ObjectItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ObjectResult) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func init() {
	proto.RegisterType((*ObjectMeta)(nil), "sko.ObjectMeta")
	proto.RegisterType((*ObjectData)(nil), "sko.ObjectData")
	proto.RegisterType((*ObjectItem)(nil), "sko.ObjectItem")
	proto.RegisterType((*ObjectReader)(nil), "sko.ObjectReader")
	proto.RegisterType((*ObjectWriter)(nil), "sko.ObjectWriter")
	proto.RegisterType((*ObjectResult)(nil), "sko.ObjectResult")
}

func init() { proto.RegisterFile("sko.proto", fileDescriptor_sko_d2bc4f079416d69d) }

var fileDescriptor_sko_d2bc4f079416d69d = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x95, 0xd8, 0x49, 0xe3, 0x89, 0x2b, 0xd0, 0x0a, 0xc1, 0x4a, 0x08, 0x29, 0x18, 0x21,
	0xe5, 0xd4, 0x03, 0x3c, 0x01, 0x94, 0x03, 0x3d, 0xd0, 0x4a, 0x8b, 0x54, 0x8e, 0xd6, 0xd6, 0x9e,
	0xc2, 0xe2, 0x38, 0x8e, 0x76, 0xc7, 0x51, 0x53, 0x5e, 0x8a, 0x17, 0xe2, 0x5d, 0xd0, 0xcc, 0xda,
	0x8d, 0xe0, 0xdc, 0xdb, 0xfc, 0xff, 0x37, 0xbb, 0x9e, 0xfd, 0x77, 0x0d, 0x59, 0x68, 0xba, 0xb3,
	0x9d, 0xef, 0xa8, 0x53, 0x49, 0x68, 0xba, 0xe2, 0xcf, 0x04, 0xe0, 0xea, 0xe6, 0x27, 0x56, 0xf4,
	0x05, 0xc9, 0xaa, 0xa7, 0x90, 0x34, 0x78, 0xd0, 0x93, 0xd5, 0x64, 0x9d, 0x1b, 0x2e, 0x95, 0x86,
	0x93, 0x3d, 0xfa, 0xe0, 0xba, 0xad, 0x9e, 0xae, 0x26, 0xeb, 0xd4, 0x8c, 0x52, 0xbd, 0x80, 0x13,
	0xb7, 0xad, 0x7c, 0xe9, 0x6a, 0x9d, 0x08, 0x99, 0xb3, 0xbc, 0xa8, 0x79, 0x49, 0xe5, 0xd1, 0x12,
	0xd6, 0x3a, 0x8d, 0x4b, 0x06, 0xc9, 0xa4, 0xdf, 0xd5, 0x42, 0x66, 0x91, 0x0c, 0x92, 0x09, 0xde,
	0xed, 0x9c, 0xc7, 0x5a, 0x2f, 0x23, 0x19, 0xa4, 0x7a, 0x05, 0x50, 0x5b, 0xb2, 0xa5, 0x25, 0xf2,
	0x41, 0xe7, 0x02, 0x33, 0x76, 0x3e, 0xb0, 0xf1, 0x80, 0xab, 0x1f, 0x58, 0x35, 0xfa, 0xf4, 0x88,
	0xcf, 0xd9, 0x28, 0x2e, 0xc7, 0xe3, 0x7d, 0xb2, 0x64, 0xd5, 0x33, 0x98, 0xc5, 0x6d, 0x16, 0xd2,
	0x17, 0x05, 0xbb, 0x71, 0x75, 0x16, 0x5d, 0x11, 0xec, 0xee, 0xed, 0xa6, 0x47, 0x0d, 0x12, 0x46,
	0x14, 0xc5, 0xf5, 0xb8, 0xdf, 0x05, 0x61, 0xab, 0xde, 0x40, 0xda, 0x22, 0x59, 0x49, 0x66, 0xf9,
	0xee, 0xc9, 0x19, 0x87, 0x7b, 0x4c, 0xd3, 0x08, 0xe4, 0x26, 0x9e, 0x47, 0x42, 0xfa, 0xb7, 0x89,
	0x67, 0x32, 0x02, 0x8b, 0xdf, 0x13, 0xc8, 0xa3, 0x69, 0xd0, 0xd6, 0xe8, 0x95, 0x82, 0xb4, 0xed,
	0x6a, 0x94, 0xab, 0x48, 0x8d, 0xd4, 0xec, 0x35, 0x78, 0x08, 0x7a, 0xba, 0x4a, 0xd6, 0xb9, 0x91,
	0x5a, 0xbd, 0x84, 0x6c, 0xe3, 0x5a, 0x47, 0xe5, 0xb6, 0x6f, 0xe5, 0x58, 0x89, 0x59, 0x88, 0x71,
	0xd9, 0xb7, 0x1c, 0x4e, 0x84, 0xc1, 0xdd, 0xa3, 0x1c, 0x2f, 0x31, 0xb1, 0xfd, 0xab, 0xbb, 0x47,
	0xc6, 0x0d, 0x1e, 0xca, 0xee, 0xf6, 0x36, 0x20, 0x49, 0xb4, 0xb9, 0xc9, 0x1a, 0x3c, 0x5c, 0x89,
	0x31, 0xe2, 0xaa, 0x27, 0xc6, 0xa7, 0x0f, 0xf8, 0x5c, 0x8c, 0xe2, 0xd7, 0x38, 0xf1, 0x37, 0xef,
	0x08, 0xfd, 0xe3, 0x85, 0xa1, 0x5e, 0x43, 0xbe, 0xf3, 0xb8, 0x2f, 0xc7, 0x87, 0x17, 0xdf, 0xca,
	0x92, 0xbd, 0xeb, 0x68, 0x1d, 0x3f, 0x6e, 0x30, 0xf4, 0x1b, 0x52, 0xcf, 0x61, 0x1e, 0xc8, 0x52,
	0x1f, 0x86, 0xc0, 0x06, 0xc5, 0xef, 0xaa, 0xc5, 0x10, 0xec, 0x77, 0x94, 0xb9, 0x32, 0x33, 0x4a,
	0xf5, 0x16, 0x66, 0x8e, 0xb0, 0x0d, 0x3a, 0x5b, 0x25, 0xff, 0x8d, 0xc2, 0x77, 0x6b, 0x22, 0xe5,
	0xcc, 0xb7, 0x78, 0x17, 0xd3, 0x59, 0x18, 0xa9, 0x3f, 0x4e, 0x3f, 0x27, 0x37, 0x73, 0xf9, 0x89,
	0xde, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xa4, 0x44, 0x6e, 0x51, 0x03, 0x00, 0x00,
}
